
services:
  mongodb:
    image: mongo:latest
    container_name: claims-mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: claimsdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: claimspass123

volumes:
  mongo_data: